name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Generate documentation
      run: docker run --rm -it -w /build -v $GITHUB_WORKSPACE:/build daux/daux.io daux
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        FOLDER: "static"
        BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
